# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dievarga <dievarga@student.42barcelon      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/09/29 13:56:25 by dievarga          #+#    #+#              #
#    Updated: 2025/09/30 11:53:12 by dievarga         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME    = ft_display_file
SRC     = display_file.c

all:
	@gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:
	@rm -f *.o

fclean: clean
	@rm -f $(NAME)

.PHONY: all clean fclean 
